<a href="https://colab.research.google.com/github/abhi01-sys/ML--Journey/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# One Hot Encoding/Nominal

In [4]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder

In [7]:
df = sns.load_dataset('tips')

In [ ]:
df

In [9]:
encoder = OneHotEncoder()

In [11]:
encoded = encoder.fit_transform(df[['sex']])

In [12]:
encoder_df = pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [13]:
encoder_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [14]:
encoder.transform([['Male']]).toarray()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 1.]])

In [15]:
pd.concat([df,encoder_df],axis=1)

     total_bill   tip     sex smoker   day    time  size  sex_Female  sex_Male
0         16.99  1.01  Female     No   Sun  Dinner     2         1.0       0.0
1         10.34  1.66    Male     No   Sun  Dinner     3         0.0       1.0
2         21.01  3.50    Male     No   Sun  Dinner     3         0.0       1.0
3         23.68  3.31    Male     No   Sun  Dinner     2         0.0       1.0
4         24.59  3.61  Female     No   Sun  Dinner     4         1.0       0.0
..          ...   ...     ...    ...   ...     ...   ...         ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         0.0       1.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         1.0       0.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         0.0       1.0
242       17.82  1.75    Male     No   Sat  Dinner     2         0.0       1.0
243       18.78  3.00  Female     No  Thur  Dinner     2         1.0       0.0

[244 rows x 9 columns]

In [26]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

#Label Encoding and Ordered Encoding

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encoder = LabelEncoder()

In [18]:
encoded = encoder.fit_transform(df['day'])

In [19]:
encoded_df = pd.DataFrame(encoded,columns=['day'])

In [20]:
encoded_df

     day
0      2
1      2
2      2
3      2
4      2
..   ...
239    1
240    1
241    1
242    1
243    3

[244 rows x 1 columns]

In [28]:
encoder.transform(['Sun', 'Sat', 'Thur', 'Fri'])

array([2, 1, 3, 0])

In [29]:
pd.concat([df,encoded_df],axis=1)

     total_bill   tip     sex smoker   day    time  size  day
0         16.99  1.01  Female     No   Sun  Dinner     2    2
1         10.34  1.66    Male     No   Sun  Dinner     3    2
2         21.01  3.50    Male     No   Sun  Dinner     3    2
3         23.68  3.31    Male     No   Sun  Dinner     2    2
4         24.59  3.61  Female     No   Sun  Dinner     4    2
..          ...   ...     ...    ...   ...     ...   ...  ...
239       29.03  5.92    Male     No   Sat  Dinner     3    1
240       27.18  2.00  Female    Yes   Sat  Dinner     2    1
241       22.67  2.00    Male    Yes   Sat  Dinner     2    1
242       17.82  1.75    Male     No   Sat  Dinner     2    1
243       18.78  3.00  Female     No  Thur  Dinner     2    3

[244 rows x 8 columns]

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
Ordinal_EN = OrdinalEncoder(categories=[['Thur','Fri','Sat','Sun']])

In [32]:
encoder = Ordinal_EN.fit_transform(df[['day']])

In [33]:
encoded_df = pd.DataFrame(encoder,columns=['day'])

In [34]:
encoded_df

     day
0    3.0
1    3.0
2    3.0
3    3.0
4    3.0
..   ...
239  2.0
240  2.0
241  2.0
242  2.0
243  0.0

[244 rows x 1 columns]

In [35]:
final_df = pd.concat([df,encoded_df],axis=1)

In [36]:
final_df

     total_bill   tip     sex smoker   day    time  size  day
0         16.99  1.01  Female     No   Sun  Dinner     2  3.0
1         10.34  1.66    Male     No   Sun  Dinner     3  3.0
2         21.01  3.50    Male     No   Sun  Dinner     3  3.0
3         23.68  3.31    Male     No   Sun  Dinner     2  3.0
4         24.59  3.61  Female     No   Sun  Dinner     4  3.0
..          ...   ...     ...    ...   ...     ...   ...  ...
239       29.03  5.92    Male     No   Sat  Dinner     3  2.0
240       27.18  2.00  Female    Yes   Sat  Dinner     2  2.0
241       22.67  2.00    Male    Yes   Sat  Dinner     2  2.0
242       17.82  1.75    Male     No   Sat  Dinner     2  2.0
243       18.78  3.00  Female     No  Thur  Dinner     2  0.0

[244 rows x 8 columns]

#Target Guided Ordinal Encoding

In [37]:
new_df = sns.load_dataset('tips')

In [38]:
from sklearn.preprocessing import TargetEncoder

In [39]:
encoder = TargetEncoder()

In [48]:
encoded = encoder.fit_transform(new_df[['day']],new_df['total_bill'])

In [53]:
df_encoded = pd.DataFrame(encoded,columns=['day_encoded_total_bill'])

In [54]:
pd.concat([new_df,df_encoded],axis=1)

,total_bill,tip,sex,smoker,day,time,size,day_encoded_total_bill
0,16.99,1.01,Female,No,Sun,Dinner,2,22.255033
1,10.34,1.66,Male,No,Sun,Dinner,3,20.959916
2,21.01,3.50,Male,No,Sun,Dinner,3,22.255033
3,23.68,3.31,Male,No,Sun,Dinner,2,21.103826
4,24.59,3.61,Female,No,Sun,Dinner,4,21.226309
...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,20.276662
240,27.18,2.00,Female,Yes,Sat,Dinner,2,20.012201
241,22.67,2.00,Male,Yes,Sat,Dinner,2,20.080759
242,17.82,1.75,Male,No,Sat,Dinner,2,20.276662
243,18.78,3.00,Female,No,Thur,Dinner,2,17.957232