In [75]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from collections import Counter

print("Import's Gets Successfull !!")

Import's Gets Successfull !!

In [76]:
df = pd.read_csv('/content/Social_Network_Ads.csv')

In [77]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [78]:
df.drop(columns=['User ID'],inplace=True)

In [79]:
encoder = LabelEncoder()
df['Gender'] = encoder.fit_transform(df['Gender'])

In [80]:
df

     Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [81]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [82]:
X

     Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [83]:
scalar = StandardScaler()
X = scalar.fit_transform(X)

In [84]:
X

array([[ 1.02020406, -1.78179743, -1.49004624],
       [ 1.02020406, -0.25358736, -1.46068138],
       [-0.98019606, -1.11320552, -0.78528968],
       ...,
       [-0.98019606,  1.17910958, -1.46068138],
       [ 1.02020406, -0.15807423, -1.07893824],
       [-0.98019606,  1.08359645, -0.99084367]])

In [85]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [86]:
Knn = KNeighborsClassifier(n_neighbors=5)
Knn.fit(X_train,y_train)

KNeighborsClassifier()

In [87]:
y_pred = Knn.predict(X_test)

In [88]:
print(accuracy_score(y_test,y_pred))

0.95

In [91]:
class KNeighborsCClassifier():

  def __init__(self,k):
    self.n_neighbour = k
    self.X_train = None
    self.y_train = None

  def fit(self,X_train,y_train):
    self.X_train = X_train
    self.y_train = y_train

  def predict(self,X_test):
    y_pred = []

    for i in X_test:
      distances = []
      for j in X_train:
        distance = np.sqrt(np.sum((i-j)**2))
        distances.append(index,distance)
        distances.sort(key=lambda x: x[1])
        n_neighbour = np.array(distances)[0:n_neighbour]
        label = self.majority_vote(n_neighbour)
        y_pred.append(label)
    return y_pred

  def majority_vote(self,n_neighbour):
    votes = []
    for i in n_neighbour:
      votes.append(i,self.y_train[i])
    votes = Counter(votes)
    votes = votes.most_common(1)[0][0]
    return votes

In [92]:
Knn1 = KNeighborsCClassifier(k=5)
Knn1.fit(X_train,y_train)

In [93]:
y_pred1 = Knn.predict(X_test)

In [94]:
print(accuracy_score(y_test,y_pred1))

0.95